version: '2'
services:
  fpm:
    build: PHP7fpm
    # restart: always
    volumes:
      - ./app:/var/www/html

    ports:
      - "9000:9000"
    #links:
    #  - mysql

  nginx:
    build: Nginx
    # restart: always
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./Logs/Nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - fpm

  #mysql:
    #image: mysql:5.7
    #restart: always
    #ports:
     # - "3306:3306"
    #environment:
     # - MYSQL_ROOT_PASSWORD=root
     # - MYSQL_DATABASE=api_db
    #volumes:
    #-   ./data/db:/var/lib/mysql
